### ISSUE TITLE
FIXED - Plugin fails if installed in a different directory

### ISSUE THREAD

**Issue by pcav** [geodrinx/rasmover#2]
Traceback (most recent call last):
  File "/home/paolo/qgis_test/python/plugins/rasmover/rasmover.py", line 155, in canvasReleaseEvent
    f2 = open(dbName+'.csv', 'w')
IOError: [Errno 2] File o directory non esistente: '/home/paolo/.qgis2/python/plugins/rasmover/temp/coords.csv'

**Comment by pcav** [comment]
I was wrong: it fails also in the standard dir.

Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/rasmover/rasmover.py", line 201, in canvasReleaseEvent
    f1  = open(fileVRT, 'r')
IOError: [Errno 2] File o directory non esistente: '\home\paolo\.qgis2\python\plugins\rasmover\temp\original.vrt'
