### ISSUE TITLE
Mac OS X - probable Python 2.6 incompatibilities

### ISSUE THREAD

**Issue by cbertelli** [geodrinx/rasmover#3]
After installing, I get:
The plugin is corrupt. Python message:
zero length field name in format
It seems an issue with python 2.6.

**Comment by geodrinx** [comment]
On MacOSX  (Mountain Lion)  RasMover does not work    :( 

Traceback (most recent call last):
  File ".qgis2/python/plugins/rasmover/rasmover.py", line 202, in canvasReleaseEvent
    subprocess.call([ "gdalbuildvrt", fileVRT, "-input_file_list", listaRaster ])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 493, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 679, in **init**
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1228, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

It seems  "gdalbuildvrt"  is not in the path …

**Comment by geodrinx** [comment]
In fact, executing from terminal:

gdalbuildvrt
dyld: Library not loaded: /usr/local/opt/sqlite/lib/libsqlite3.0.8.6.dylib
  Referenced from: /usr/local/bin/gdalbuildvrt
  Reason: image not found
Trace/BPT trap: 5

How to solve it ?
