### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by SzieberthAdam** [geodrinx/rasmover#9]
Maybe because of accented filename:

```
Traceback (most recent call last):
  File "C:/Documents and Settings/ti2/.qgis2/python/plugins\rasmover\rasmover.py", line 192, in canvasReleaseEvent
    f5.write( scrivimi )
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 7: ordinal not in range(128)
```

**Comment by geodrinx** [comment]
Hi Adam,
thanks for your issue track.
Anyway, I inform you that I removed "rasmover"  in official QGIS plugin repository, and I do not want to develop plug-ins for such software more.
For you, I will do an exception, and I will correct the bug,  inserting a new version in github, at this link:
https://github.com/geodrinx/rasmover/

So stay tuned and control for updates.

Roberto

**Comment by SzieberthAdam** [comment]
Thanks for your kindness!

However, it is now fixed.

**Comment by chiccogen** [comment]
Hello everybody,
I encountered the same problem:
An error has occurred while executing Python code: 

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 30: ordinal not in range(128) 
Traceback (most recent call last):
  File "C:/Users/Chiccogen/.qgis2/python/plugins\rasmover\rasmover.py", line 192, in canvasReleaseEvent
    f5.write( scrivimi )
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 30: ordinal not in range(128)


Versione Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Versione di QGIS: 2.18.4 Las Palmas, 59c1d21

**Comment by geodrinx** [comment]
Sorry I have just deleted my "rasmover" plugin from the official QGIS repository and I do not intend to support it.

Roberto (GeoDrinX)
